[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cd server',
  'npm ci --only=production'
]

[phases.build]
cmds = [
  'cd server',
  'npm run logs'
]

[start]
cmd = 'cd server && npm start'

[variables]
NODE_ENV = 'production'
PORT = '3000'